# Generated by Django 4.1.8 on 2025-11-26 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysystem', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='产品名称')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='价格')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否上架')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '测试产品表',
                'db_table': 'zane_product',
            },
        ),
    ]
