# Generated by Django 4.1.8 on 2025-11-27 18:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import utils.models


class Migration(migrations.Migration):

    dependencies = [
        ('mysystem', '0002_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='create_datetime',
            field=models.DateTimeField(auto_now_add=True, help_text='创建时间', null=True, verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='product',
            name='creator',
            field=models.ForeignKey(db_constraint=False, help_text='创建人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_query_name='creator_query', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='product',
            name='dept_belong',
            field=models.CharField(blank=True, help_text='数据归属部门', max_length=100, null=True, verbose_name='数据归属部门'),
        ),
        migrations.AddField(
            model_name='product',
            name='modifier',
            field=models.CharField(blank=True, help_text='修改人', max_length=100, null=True, verbose_name='修改人'),
        ),
        migrations.AddField(
            model_name='product',
            name='update_datetime',
            field=models.DateTimeField(auto_now=True, help_text='修改时间', null=True, verbose_name='修改时间'),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.CharField(default=utils.models.make_uuid, help_text='Id', max_length=100, primary_key=True, serialize=False, verbose_name='Id'),
        ),
    ]
